# Generated by Django 5.2.13 on 2026-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenio',
            old_name='tipo',
            new_name='tipo_acuerdo',
        ),
        migrations.AddField(
            model_name='actor',
            name='tipo',
            field=models.CharField(default='Gobierno Provincial', max_length=50),
            preserve_default=False,
        ),
    ]
