# Generated by Django 5.2.13 on 2026-06-28 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tipo_convenio_tipo_acuerdo_actor_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='anio',
        ),
        migrations.AddField(
            model_name='convenio',
            name='actores',
            field=models.ManyToManyField(related_name='convenios', to='core.actor'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='enlace_documento',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Finalizado', 'Finalizado'), ('Suspendido', 'Suspendido')], default='Vigente', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convenio',
            name='fecha_firma',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convenio',
            name='tema',
            field=models.CharField(default='Sin clasificar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convenio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
