# Generated by Django 5.2.13 on 2026-06-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_convenio_actor_remove_convenio_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='enlace_documento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='tema',
            field=models.CharField(choices=[('Comercio', 'Comercio'), ('Turismo', 'Turismo'), ('Cultura', 'Cultura'), ('Educación', 'Educación'), ('Ambiente', 'Ambiente'), ('Salud', 'Salud'), ('Energía', 'Energía'), ('Ciencia y Tecnología', 'Ciencia y Tecnología'), ('Cooperación Institucional', 'Cooperación Institucional'), ('Otro', 'Otro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='tipo_acuerdo',
            field=models.CharField(choices=[('Convenio Marco', 'Convenio Marco'), ('Convenio Específico', 'Convenio Específico'), ('Memorándum de Entendimiento', 'Memorándum de Entendimiento'), ('Carta de Intención', 'Carta de Intención'), ('Protocolo', 'Protocolo'), ('Acuerdo de Cooperación', 'Acuerdo de Cooperación'), ('Otro', 'Otro')], max_length=40),
        ),
    ]
